feat: update grub2 to 2.12-1

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -301,7 +301,9 @@ config_item()
 {
   for x in /etc/default/grub /etc/default/grub.d/*.cfg; do
     if [ -e "$x" ]; then
-      . "$x"
+	# Lose any output here so we don't confuse our
+	# caller. The xen packages echo stuff here, Aargh!
+      . "$x" > /dev/null
     fi
   done
   if [ "$(eval echo "\${$1+set}")" = set ]; then
@@ -393,6 +395,19 @@ case "$1" in
     apply_conf_tweaks "$conf_files" merge_debconf_into_conf GRUB_CMDLINE_LINUX grub2/linux_cmdline
     apply_conf_tweaks "$conf_files" merge_debconf_into_conf GRUB_CMDLINE_LINUX_DEFAULT grub2/linux_cmdline_default
 
+    # Horrible stuff here, as the os-prober option is a negative
+    # setting (GRUB_DISABLE_OS_PROBER). To not confuse people with
+    # double negative questions in templates, invert it here.
+    db_get grub2/enable_os_prober
+    if [ "$RET" = false ]; then
+      # enable == false -> put in place the commented-out default
+      # #GRUB_DISABLE_OS_PROBER=false that we ship with
+      apply_conf_tweaks "$conf_files" sed_conf 's/^.*GRUB_DISABLE_OS_PROBER.*$/#GRUB_DISABLE_OS_PROBER=false/'
+    else
+      # enable == true -> put in place a valid GRUB_DISABLE_OS_PROBER=false
+      apply_conf_tweaks "$conf_files" sed_conf 's/^.*GRUB_DISABLE_OS_PROBER.*$/GRUB_DISABLE_OS_PROBER=false/'
+    fi
+
     case @PACKAGE@ in
       grub-pc)
         apply_conf_tweaks "$conf_files" merge_debconf_into_conf GRUB_TIMEOUT grub-pc/timeout
@@ -402,6 +417,15 @@ case "$1" in
           apply_conf_tweaks "$conf_files" sed_conf 's/^GRUB_HIDDEN_TIMEOUT=/#&/'
         fi
       ;;
+      grub-ieee1275)
+        if grep ^platform /proc/cpuinfo | grep -q PowerNV; then
+		cat <<-EOF >>"$tmp_default_grub"
+
+		# Disable os-prober for ppc64el on the PowerNV platform (for Petitboot)
+		GRUB_DISABLE_OS_PROBER=true
+		EOF
+        fi
+        ;;
     esac
 
     # If the template configuration file hasn't changed, then no conflict is
@@ -568,16 +592,21 @@ case "$1" in
             db_go
             db_get "$question"
             failed_devices=
+            echo "@PACKAGE@: Running grub-install ..."
             for i in $RET; do
               real_device="$(readlink -f "${i%,}")"
               if [ ! -e "$real_device" ]; then
                 echo "$real_device does not exist, so cannot grub-install to it!" >&2
                 failed_devices="$failed_devices $real_device"
-              elif grub-install --target=i386-pc --force --no-floppy $real_device ; then
-                # We just installed GRUB 2; then also generate grub.cfg.
-                touch /boot/grub/grub.cfg
               else
-                failed_devices="$failed_devices $real_device"
+                if grub-install --target=i386-pc --force --no-floppy $real_device ; then
+                  echo "  grub-install success for $real_device"
+                  # We just installed GRUB 2; then also generate grub.cfg.
+                  touch /boot/grub/grub.cfg
+                else
+                  echo "  grub-install failure for $real_device"
+                  failed_devices="$failed_devices $real_device"
+                fi
               fi
             done
 
@@ -632,7 +661,7 @@ case "$1" in
                   echo >&2
                   echo "  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc" >&2
                   echo "  dpkg --configure -a" >&2
-		  break
+                  exit 1 # noninteractive
                 fi
               fi
             fi
@@ -663,7 +692,7 @@ case "$1" in
                   echo >&2
                   echo "  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc" >&2
                   echo "  dpkg --configure -a" >&2
-		  break
+                  exit 1 # noninteractive
                 fi
               fi
             else
@@ -690,21 +719,22 @@ case "$1" in
         fi
       ;;
 
-      grub-efi-ia32|grub-efi-amd64|grub-efi-ia64|grub-efi-arm|grub-efi-arm64)
+      grub-efi-ia32|grub-efi-amd64|grub-efi-ia64|grub-efi-arm|grub-efi-arm64|grub-efi-riscv64)
         bootloader_id="$(config_item GRUB_DISTRIBUTOR | tr A-Z a-z | \
                          cut -d' ' -f1)"
         case $bootloader_id in
           kubuntu) bootloader_id=ubuntu ;;
           devuan) bootloader_id=debian ;;
         esac
-        if [ "$bootloader_id" ] && [ -d "/boot/efi/EFI/$bootloader_id" ]; then
-          case @PACKAGE@ in
-            grub-efi-ia32)  target=i386-efi ;;
-            grub-efi-amd64) target=x86_64-efi ;;
-            grub-efi-ia64)  target=ia64-efi ;;
-            grub-efi-arm)   target=arm-efi ;;
-            grub-efi-arm64) target=arm64-efi ;;
-          esac
+        case @PACKAGE@ in
+          grub-efi-ia32)  target=i386-efi ;;
+          grub-efi-amd64) target=x86_64-efi ;;
+          grub-efi-ia64)  target=ia64-efi ;;
+          grub-efi-arm)   target=arm-efi ;;
+          grub-efi-arm64) target=arm64-efi ;;
+          grub-efi-riscv64) target=riscv64-efi ;;
+        esac
+        if [ "$bootloader_id" ] && [ -e "/boot/grub/$target/core.efi" ]; then
           db_get grub2/force_efi_extra_removable
           if [ "$RET" = true ]; then
             FORCE_EXTRA_REMOVABLE="--force-extra-removable"
@@ -739,11 +769,6 @@ case "$1" in
 
       grub-yeeloong)
         run_grub_install --target=mipsel-loongson
-      ;;
-
-      grub-efi-loongarch64)
-        # run_grub_install --target=loongarch64-efi
-	grub-mkimage -v -o /EFI/BOOT/BOOTLOONGARCH.EFI  -O loongarch64-efi -d /usr/lib/grub/loongarch64-efi/ -p /boot/EFI ext2 fat iso9660 part_msdos part_gpt  configfile cat echo sleep test halt reboot minicmd search font loadenv linux
       ;;
 
       grub-xen)
